[build]
  command = "npm install && npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20", NPM_FLAGS = "--legacy-peer-deps", PYTHON_VERSION = "3.11", SECRETS_SCAN_ENABLED = "false" }

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self' https://onebreath-react.onrender.com https://*.firebaseapp.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.firebaseapp.com https://*.googleapis.com https://unpkg.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https: blob:;
      connect-src 'self' https://onebreath-react.onrender.com https://*.firebaseapp.com https://*.googleapis.com https://identitytoolkit.googleapis.com;
      frame-src 'self' https://*.firebaseapp.com https://*.googleapis.com;
      font-src 'self' data:;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      media-src 'self' blob:;
      worker-src 'self' blob:;
    """
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
