services:
  - type: web
    name: flask-api
    env: python
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: cd src/server && gunicorn --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  - type: web
    name: react-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
