services:
  - type: web
    name: flask-api
    env: python
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: ./run.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: FLASK_APP
        value: wsgi:app
